---

MODEL:
    THRESHOLD: 0.25
    NAME: "resnet50"
    NUM_CLASSES: 5
OUTPUT_DIR: "outputs/resnet50"
TRAINER:
    LR: 3e-2
INPUT:
    TRANSFORM:
        RAND_GAUSS:
            ACTIVE: True
            INTENSITY: 0.35
        LENGTH: 40960
    RECORD_LENGTH: 40960
...
