---

MODEL:
    THRESHOLD: 0.25
    NAME: "resnet50"
    NUM_CLASSES: 5
OUTPUT_DIR:
    "outputs/resnet50_rg_105"
TRAINER:
    LR: 3e-2
INPUT:
    TRANSFORM:
        RAND_GAUSS:
            ACTIVE: True
            INTENSITY: 1.05
...
